### ISSUE TITLE
Hardcoded username and endless loop tests didn't work 

### ISSUE THREAD

**Issue by helsonqduarte** [OWASP/abap-code-scanner#1]
Hi there!
I tried ABAP-Code-Analyzer with the "python main.py ABAPTeste02ListagemdeOV.txt" command. ABAPTeste02ListagemdeOV.txt ( attached) file was in the same directory than ABAP-Code-Analyzer.
The xls output file was generated with no lines (attached).
I had understood ABAP-Code-Analyzer should "caught" hardcode user name and endless loop...
Thanks!
[abap_security_scan_report.xlsx](https://github.com/user-attachments/files/16932297/abap_security_scan_report.xlsx)
[ABAPTeste02ListagemdeOV.txt](https://github.com/user-attachments/files/16932299/ABAPTeste02ListagemdeOV.txt)

**Comment by vah13** [comment]
Hello, yes. 
You touch on very important questions that will be handled in the data-flow part.

if you modify your code from 
```
IF LV_UNAME = 'HELSON.DUARTE'.
```
to
```
IF SY-UNAME = 'HELSON.DUARTE'.
```

The scanner will detect the issue. 
![image](https://github.com/user-attachments/assets/c4bc56f8-f47d-4448-a10b-132b6f39b370)

In a few months, we will release, maybe in public, the data-flow part that will also detect this kind of vulnerability. 

Thank you

**Comment by helsonqduarte** [comment]
It worked for ne user name!
In wich scenario the CheckDosInDoLoop test works?

**Comment by vah13** [comment]
After analyzing your ABAP code, you can filter out the use of the `DO ... TIMES` construct with large numbers. This will help identify potential problem areas where long loops or redundant iterations may occur.

**Comment by vah13** [comment]
Please check our new version of the scanner.  

https://redrays.io/abap-scanner/
